# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: serverless
      POSTGRES_PASSWORD: 15987532
    ports:
      - 6543:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
