service: user-crud
# variablesResolutionMode: 20210326
configValidationMode: off

custom:
  myStage: ${file(../../serverless.common.yml):custom.myStage}
  variables: ${file(../../serverless.common.yml):custom.variables}
  vpc:
    securityGroupIds:
      - sg-972c0eab
    subnetIds:
      - subnet-3be47166
      - subnet-d47d70ff
      - subnet-c03289b8
      - subnet-3784207d

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${self:custom.myStage}
  region: us-west-2
  profile: serverless
  environment: ${file(../../serverless.common.yml):provider.environment}

functions:
  createUser:
    handler: create/index.handler
    vpc: ${self:custom.vpc}
    package:
      patterns:
        - "create/**"
        - "../utils/**"

    events:
      - http:
          path: users/
          method: POST
          request:
            schemas:
              application/json:
                schema: ${file(../utils/database/models/User.js):SchemaValidator}
                name: CreateUserModel
                description: "Validation for User creation"
  updateUser:
    handler: update/index.handler
    vpc: ${self:custom.vpc}
    package:
      patterns:
        - "update/**"
        - "../utils/**"
    events:
      - http:
          path: users/{id}
          method: PUT
  deleteUser:
    handler: delete/index.handler
    vpc: ${self:custom.vpc}
    package:
      patterns:
        - "delete/**"
        - "../utils/**"
    events:
      - http:
          path: users/{id}
          method: DELETE
  findAllUsers:
    handler: findAll/index.handler
    vpc: ${self:custom.vpc}
    package:
      patterns:
        - "findAll/**"
        - "../utils/**"
    events:
      - http:
          path: users/
          method: GET
  findOneUser:
    handler: findOne/index.handler
    vpc: ${self:custom.vpc}
    package:
      patterns:
        - "findOne/**"
        - "../utils/**"
    events:
      - http:
          path: users/{id}
          method: GET

package:
  individually: true
  patterns:
    - "!**/*"

plugins:
  - serverless-offline
